### Database

#List
GET https://api.notion.com/v1/databases
Content-Type: application/json
Authorization: Bearer {{token}}
Notion-Version: 2021-08-16

###
# Query
POST https://api.notion.com/v1/databases/b382c100-1fea-48b3-a503-72e86583ee4c/query
Content-Type: application/json
Authorization: Bearer {{token}}
Notion-Version: {{api_version}}

###
# Create
POST https://api.notion.com/v1/databases/
Content-Type: application/json
Authorization: Bearer {{token}}
Notion-Version: {{api_version}}

{
  "parent": {
    "type": "page_id",
    "page_id": "{{page_id}}"
  },
  "title": [
    {
      "type": "text",
      "text": {
        "content": "Grocery List",
        "link": null
      }
    }
  ],
  "properties": {
    "Name": {
      "title": {}
    },
    "create": {
      "type": "rich_text",
      "rich_text": {}
    }
  }
}

### Page
# Get
GET https://api.notion.com/v1/pages/{{page_id}}
Content-Type: application/json
Authorization: Bearer {{token}}
Notion-Version: {{api_version}}


### Block
# Get
GET https://api.notion.com/v1/blocks/a7bde50e-23ca-4317-b71c-35a2daff9a2d
Content-Type: application/json
Authorization: Bearer {{token}}
Notion-Version: {{api_version}}


###
# Retrieve Block Children
GET https://api.notion.com/v1/blocks/{{block_id}}/children
Content-Type: application/json
Authorization: Bearer {{token}}
Notion-Version: {{api_version}}


###
# Update
PATCH  https://api.notion.com/v1/blocks/{{block_id}}
Content-Type: application/json
Authorization: Bearer {{token}}
Notion-Version: {{api_version}}

{
  "paragraph": {
    "text": [{
      "text": { "content": "Lacinato kale" }
    }]
  }
}
